#?install ~/.bash_logout -*-sh-*-
#
# bash_logout - This file is sourced when a login shell terminates.
#

# Clear the screen, except for remote (SSH) sessions and local
# Terminal windows.
if [ -z "$SSH_CLIENT" ] && [ -z "$TERM_PROGRAM" ]; then
    # Prefer clear_console because it clears the VT scrollback as well.
    clear_console 2>/dev/null || clear
fi
